# Generated by Django 4.1.4 on 2023-05-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0029_delete_test_result_delete_category_delete_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': False, 'verbose_name': 'Ariza va shikoyat', 'verbose_name_plural': 'Ariza va shikoyatlar'},
        ),
    ]
