# Generated by Django 4.1.4 on 2023-05-03 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0030_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
    ]
