# Generated by Django 4.1.4 on 2023-05-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0032_information_murojat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': False, 'verbose_name': 'Ariza', 'verbose_name_plural': 'Arizalar'},
        ),
        migrations.AlterModelOptions(
            name='murojat',
            options={'verbose_name': 'Shikoyat va Muammo', 'verbose_name_plural': 'Shikoyat va Muammolar'},
        ),
        migrations.AlterModelOptions(
            name='user_test',
            options={'verbose_name': 'Taklif', 'verbose_name_plural': 'Takliflar'},
        ),
    ]
